apiVersion: v1
kind: ServiceAccount
metadata:
  name: mutation-test-sa
  annotations:
    workload-identity.stackit.cloud/service-account-email: "yourserviceaccount@sa.stackit.cloud"
---
apiVersion: v1
kind: Pod
metadata:
  name: mutation-test-pod
spec:
  serviceAccountName: mutation-test-sa
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sleep", "3600"]
