apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  annotations:
    workload-identity.stackit.cloud/service-account-email: "test-sa@stackit.cloud"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  serviceAccountName: test-sa
  containers:
  - name: nginx
    image: nginx
